name: AetherPotions
version: '${project.version}'
main: com.kardasland.aetherpotions.AetherPotions
api-version: 1.15
authors: [KardasLand]
description: A customizable potion plugin.
website: www.kardasland.com
commands:
  aetherpotions:
    aliases:
      - ap

